run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  errcheck:
    check-type-assertions: true
    check-blank: false
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - github.com/danielgtaylor/huma/v2.WriteErr
      - (*github.com/jackc/pgx/v5.Tx).Rollback
  gocyclo:
    min-complexity: 30
  gocognit:
    min-complexity: 60
  gosec:
    excludes:
      - G115

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - gosec
    - gocyclo
    - gocognit
    - misspell
    - unconvert
    - unparam
    - prealloc
    - bodyclose

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - gocognit
